name: Run Deployment on Proxmox

on:
  workflow_dispatch:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH into Proxmox
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROXMOX_HOST }}
          username: ${{ secrets.PROXMOX_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 8022
          script: |
            cd /etc/AIAPI
            nohup python3 deployment.py &
