name: Deploy to Proxmox

on:
  workflow_dispatch:
  push:
    branches:
      - main  # Adjust if you want to deploy on a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install sshpass
      run: apt-get install -y sshpass

    - name: Deploy to Proxmox
      env:
        PROXMOX_USER: ${{ secrets.PROXMOX_USER }}
        PROXMOX_HOST: ${{ secrets.PROXMOX_HOST }}
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      run: |
        echo "Starting deployment to Proxmox"

        # Update and install necessary packages
        echo "Updating package list and installing required packages..."
        apt update
        apt install -y git python3 python3-pip
        echo "Packages installed successfully."

        # Clone the repository
        if [ ! -d /etc/AIAPI ]; then
          echo "Cloning repository to /etc/AIAPI..."
          git clone https://github.com/Aman12b/AI_CATvDOG_API.git /etc/AIAPI
          echo "Repository cloned successfully."
        else
          echo "Repository already exists. Pulling latest changes..."
          cd /etc/AIAPI
          git pull origin main
          echo "Repository updated successfully."
        fi

        # Navigate to the repository and install dependencies
        echo "Installing Python dependencies..."
        cd /etc/AIAPI
        pip3 install -r requirements.txt
        echo "Python dependencies installed successfully."

        # Stop the existing service (if running)
        echo "Stopping existing service if running..."
        systemctl stop my-python-app.service || true
        echo "Service stopped (if it was running)."

        # Create systemd service (if needed)
        if [ ! -f /etc/systemd/system/my-python-app.service ]; then
          echo "Creating systemd service file..."
          echo "[Unit]
          Description=AIAPI
          After=network.target

          [Service]
          User=$PROXMOX_USER
          WorkingDirectory=/etc/AIAPI
          ExecStart=/usr/bin/python3 /etc/AIAPI/Prediction.py
          Restart=always

          [Install]
          WantedBy=multi-user.target" | tee /etc/systemd/system/my-python-app.service
          echo "Systemd service file created."

          echo "Enabling systemd service..."
          systemctl enable my-python-app.service
          echo "Systemd service enabled."
        fi

        # Start or restart the service
        echo "Starting or restarting the systemd service..."
        systemctl start my-python-app.service || systemctl restart my-python-app.service
        echo "Systemd service started or restarted successfully."

        echo "Deployment to Proxmox completed successfully."
