name: Deploy to Proxmox

on:
  workflow_dispatch:
  push:
    branches:
      - main  # Adjust if you want to deploy on a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    - name: Deploy to Proxmox
      env:
        PROXMOX_USER: ${{ secrets.PROXMOX_USER }}
        PROXMOX_HOST: ${{ secrets.PROXMOX_HOST }}
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      run: |
        # Update and install necessary packages
        sudo apt update
        sudo apt install -y git python3 python3-pip

        # Clone the repository
        if [ ! -d /etc/AIAPI ]; then
          sudo git clone https://github.com/Aman12b/AI_CATvDOG_API.git /etc/AIAPI
        else
          cd /etc/AIAPI
          sudo git pull origin main
        fi

        # Navigate to the repository and install dependencies
        cd /etc/AIAPI
        sudo pip3 install -r requirement.txt

        # Stop the existing service (if running)
        sudo systemctl stop my-python-app.service || true

        # Run the application in the background
        sudo python3 Prediction.py &

        # Sleep for a few seconds to ensure the process has started
        sleep 5

        # Create systemd service (if needed)
        if [ ! -f /etc/systemd/system/my-python-app.service ]; then
          echo "[Unit]
          Description=AIAPI
          After=network.target

          [Service]
          User=$PROXMOX_USER
          WorkingDirectory=/etc/AIAPI
          ExecStart=/usr/bin/python3 /etc/AIAPI/Prediction.py
          Restart=always

          [Install]
          WantedBy=multi-user.target" | sudo tee /etc/systemd/system/my-python-app.service

          sudo systemctl enable my-python-app.service
          sudo systemctl start my-python-app.service
        else
          sudo systemctl restart my-python-app.service
        fi
